### ISSUE TITLE
Attempt to view non-existant report

### ISSUE THREAD

**Issue by glittle** [glittle/TallyJ-2.0#50]
Error is log:

```
"Could not resolve template D:\home\site\wwwroot\Reports\.cshtml
   at RazorEngine.Templating.ResolvePathTemplateManager.ResolveFilePath(String name)
   at RazorEngine.Templating.ResolvePathTemplateManager.GetKey(String name, ResolveType resolveType, ITemplateKey context)
   at RazorEngine.Templating.RazorEngineService.GetKey(String cacheName, ResolveType resolveType, ITemplateKey context)
   at RazorEngine.Templating.DynamicWrapperService.GetKey(String name, ResolveType resolveType, ITemplateKey context)
   at RazorEngine.Templating.RazorEngineServiceExtensions.<>c__DisplayClass16_0.<RunCompile>b__0(TextWriter writer)
   at RazorEngine.Templating.RazorEngineServiceExtensions.WithWriter(Action`1 withWriter)
   at RazorEngine.Templating.RazorEngineServiceExtensions.RunCompile(IRazorEngineService service, String name, Type modelType, Object model, DynamicViewBag viewBag)
   at TallyJ.Code.Helpers.MvcViewRenderer.RenderRazorViewToString(String pathToView, Object model) in C:\Users\LSA Secretary\Documents\Bahai\Glen\TallyJ\V2d\Server\Site\Site\Code\Helpers\MvcViewRenderer.cs:line 26
   at TallyJ.CoreModels.ResultsModel.GetReportData(String code) in C:\Users\LSA Secretary\Documents\Bahai\Glen\TallyJ\V2d\Server\Site\Site\CoreModels\ResultsModel.cs:line 305"
```

**Comment by glittle** [comment]
Can't reproduce, but have put in checks to handle this.
